name: Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Version name (default is ref name)'

env:
  # $VERSION is used by release scripts
  VERSION: ${{ github.event.inputs.name || github.ref_name }}

jobs:
  build-scrcpy-server:
    runs-on: ubuntu-latest
    env:
      GRADLE: gradle  # use native gradle instead of ./gradlew in scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build
        run: release/build_server.sh

      - name: Upload R2
        env:
          FERY_SECRET_KEY: ${{ secrets.FERY_SECRET_KEY }}
        run: |
          curl -L https://fery.seiya.dev/bin/fery -o fery
          chmod +x ./fery
          ./fery put -f release/work/build-server/server/scrcpy-server r2p:/bin/scrcpy-server

  build-aarch64-scrcpy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prepare runtime envoriment
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support debootstrap
          # Ensure the qemu-aarch64 handler is correctly registered for cross-compilation
          sudo update-binfmts --package qemu-user-static --remove qemu-aarch64 /usr/bin/qemu-aarch64-static
          sudo update-binfmts \
            --package qemu-user-static \
            --install qemu-aarch64 /usr/bin/qemu-aarch64-static \
            --magic '\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00' \
            --mask '\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff' \
            --offset 0 \
            --credential yes \
            --fix-binary yes
          curl "https://fery.seiya.dev/seiya-deploy/chroot-build/debian-arm64-android.rootfs.tgz" -o debian.tgz
          mkdir rootfs
          sudo tar -xzf debian.tgz -C rootfs
          sudo mount -t proc proc rootfs/proc
          sudo mount -t sysfs sysfs rootfs/sys
          sudo mount -o bind /dev rootfs/dev
          sudo mount -t devpts devpts rootfs/dev/pts
          sudo mkdir -p rootfs/root/scrcpy
          sudo mount -o bind `pwd` `pwd`/rootfs/root/scrcpy
          sudo chroot rootfs /bin/bash <<-EOF
          apt install -y ffmpeg libsdl2-2.0-0 adb libusb-1.0-0
          apt install -y gcc git pkg-config meson ninja-build libsdl2-dev \
                 libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
                 libswresample-dev libusb-1.0-0-dev
          apt install -y openjdk-21-jdk
          cd /root/scrcpy
          meson setup x --buildtype=release --strip -Db_lto=true
          ninja -Cx
          EOF

      - name: Upload R2
        env:
          FERY_SECRET_KEY: ${{ secrets.FERY_SECRET_KEY }}
        run: |
          curl -L https://fery.seiya.dev/bin/fery -o fery
          chmod +x ./fery
          ./fery put -f x/app/scrcpy r2p:/bin/scrcpy/crcpy-aarch64-unknow-linux-gnu
